name: Modulo Avançado

on:
  schedule: # Executa com o agendamento às 23:59
    - cron: 52 8 * * *
  workflow_dispatch: # Roda clicando num botão que está no Github

jobs:
  deploy:
    name: "Dispara com Agendamento e Manualmente"
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar ambiente herdadoe e precedente
        run: |
          echo "Executado com sucesso"
